[package]
name = "montrs-orm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"], optional = true }
tokio-postgres = { version = "0.7", optional = true }
deadpool-postgres = { version = "0.12", optional = true }
serde.workspace = true
thiserror.workspace = true
async-trait.workspace = true
anyhow.workspace = true
tracing.workspace = true
montrs-core = { path = "../core" }

[features]
default = []
sqlite = ["dep:rusqlite"]
postgres = ["dep:tokio-postgres", "dep:deadpool-postgres"]
