[project]
name = "my-workspace"

[build]
target = "index.html"
dist = "dist"
site_root = "target/site"
site_pkg_name = "pkg"
# tailwind-input-file = "style/tailwind.css"
# tailwind-config-file = "tailwind.config.js"
# style-file = "style/main.scss"

[serve]
port = 8080
addr = "127.0.0.1"

[tasks]
dev = "cargo mont watch"
build = "cargo mont build --release"
lint = { command = "cargo clippy --workspace -- -D warnings", category = "Quality" }
fmt = { command = "cargo fmt --all", category = "Quality" }
test = { command = "cargo test --workspace", category = "Testing" }
