[package]
name = "end2end"
version = "0.1.0"
edition = "2024"

[dependencies]
montrs-test = { path = "../../../packages/test", features = ["e2e"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
