[package]
name = "web"
version.workspace = true
edition.workspace = true

[dependencies]
montrs-core = { workspace = true }
leptos = { workspace = true }
tailwind-fuse = { workspace = true }
ui = { path = "../../packages/ui" }
