[package]
name = "end2end"
version = "0.1.0"
edition = "2024"

[dependencies]
playwright = { path = "../../../../playwright-rust/crates/playwright" }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
